services:
  # Un service web gratuit
  - type: web
    name: test
    region: frankfurt
    runtime: node
    plan: free
    repo: https://github.com/Nassimbklh/blueprint
    branch: master
    buildCommand: npm install
    startCommand: npm start
    enVars:
      - key: DATABASE_URL
        fromDatabase:
          name: cloud-db
          property: connectionString

database:
  - name: cloud-db
    region: frankfurt
    plan: free
    databaseName: cloud
    user: cloud
    
