services:
  # A Docker web service
  - type: web
    name: test
    runtime: node
    region: frankfurt
    plan: free
    #branch: master
    #rootDir: default
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: cloud-db
          property: connectionString

databases:
  - name: cloud-db
    region: frankfurt
    databaseName: cloud
    user: cloud
    plan: free

